### ISSUE TITLE
Pagination des onglets publique, communautaire, privée afin de charger un petit nombre de canvas en même temps

### ISSUE THREAD

**Issue by SpicyPaper** [HE-Arc/PayPixPlace#25]

**Comment by Ishydo** [comment]
Si vous n'avez pas prévu de partir sur un code full-custom, django vous permettra de gagner pas mal de temps https://docs.djangoproject.com/fr/2.1/topics/pagination/

**Comment by SpicyPaper** [comment]
Merci de l'info @Ishydo, on en tiendra compte au moment d'attaquer cette partie.
